include classpath("application.conf")

storage = obsidian

obsidian {
    repoUrl = ${?OBSIDIAN_REPO_URL}
    token = ${?OBSIDIAN_REPO_TOKEN}
    branch = ${?OBSIDIAN_REPO_BRANCH}
    cloneDir = ${?OBSIDIAN_CLONE_DIR}
}
